version: '2'

services:
  php:
    image: akhmelik/php7
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/www:/var/www/html"
      - "./apache2/vhosts:/etc/apache2/from-host"
      - "/etc/hosts:/etc/hosts"
      #- "./php/php.ini:/etc/php/7.0/apache2/php.ini"
    links:
      - "db:db"
  db:
    image: mysql
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=secret
      - MYSQL_ROOT_PASSWORD=12345
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"
       # for mysql container
            # docker-compose exec db sh
            #CREATE USER 'sroot'@'%' IDENTIFIED BY '12345';
            #GRANT ALL PRIVILEGES ON *.* TO 'eqbeat_all'@'%';